// Generates one deliberately-wrong stub per frozen decision, each a MINIMAL edit away from the
// canonical engine.mjs. Running the same conformance vectors against a stub makes our own assertion
// fire, which is what distinguishes a real counter-example from a missing-file failure.
//
//   node stubs/build.mjs           regenerate the stubs
//   node stubs/run.mjs             run the vectors against each and print which assertions fired
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const source = readFileSync(join(here, '..', 'engine.mjs'), 'utf8')

const apply = (text, edits) => {
  let out = text
  for (const [from, to] of edits) {
    if (!out.includes(from)) throw new Error(`stub edit no longer matches engine.mjs:\n${from.slice(0, 120)}`)
    out = out.replaceAll(from, to)
  }
  return out
}

export const FLIPS = [
  {
    name: 'busy-timeout-after-version-probe',
    claim: 'busy_timeout must be the first statement on a connection',
    edits: [[
      `    // busy_timeout must be the FIRST statement on the connection. It defaults to 0, so any earlier
    // statement runs with no busy handler at all and loses a contended lock immediately -- measured:
    // that made the version probe the flakiest statement in the whole engine.
    db.exec(\`PRAGMA busy_timeout=\${busyTimeoutMs}\`)
    const version = db.prepare('SELECT sqlite_version() AS v').get().v`,
      `    const version = db.prepare('SELECT sqlite_version() AS v').get().v
    db.exec(\`PRAGMA busy_timeout=\${busyTimeoutMs}\`)`,
    ]],
  },
  {
    name: 'producer-minted-message-id',
    claim: 'message_id is protocol-generated and is not part of the payload hash',
    edits: [
      [`  if ('messageId' in input) {
    fail('PROTOCOL_MESSAGE_INVALID', 'messageId is generated by the protocol; producers must not supply one')
  }`,
        `  const suppliedMessageId = typeof input.messageId === 'string' && input.messageId
    ? input.messageId
    : randomBytes(16).toString('hex')`],
      [`  const envelope = { protocolVersion, targetSessionId, senderSessionId, kind, headers, body }
  return { ...envelope, idempotencyKey, headersJson, payloadHash: payloadHash(envelope) }`,
        `  const envelope = { protocolVersion, targetSessionId, senderSessionId, kind, headers, body }
  const hash = createHash('sha256').update(canonicalPreimage(envelope)).update(suppliedMessageId).digest()
  return { ...envelope, suppliedMessageId, idempotencyKey, headersJson, payloadHash: hash }`],
      [`    const messageId = randomBytes(16).toString('hex')`, `    const messageId = message.suppliedMessageId`],
    ],
  },
  {
    name: 'whole-schema-checksum',
    claim: 'each migration checksums only its own bytes',
    edits: [[
      `].map(m => ({ ...m, checksum: createHash('sha256').update(Buffer.from(m.sql, 'utf8')).digest('hex') }))`,
      `].map(m => ({ ...m, checksum: createHash('sha256').update(Buffer.from(m.sql + REGISTRY_SQL, 'utf8')).digest('hex') }))`,
    ]],
  },
  {
    name: 'unvalidated-session-id',
    claim: 'session ids are validated in memory; STRICT is not input validation',
    edits: [
      [`function requireSessionId(value, what = 'sessionId') {
  if (typeof value !== 'string') fail('PROTOCOL_SESSION_ID_INVALID', \`\${what} must be a string\`)
  if (value.length < 1 || value.length > LIMITS.sessionId) {
    fail('PROTOCOL_SESSION_ID_INVALID', \`\${what} must be 1..\${LIMITS.sessionId} characters\`)
  }
  if (!SESSION_ID_RE.test(value)) {
    fail('PROTOCOL_SESSION_ID_INVALID', \`\${what} must match [0-9A-Za-z_][0-9A-Za-z_-]* (got \${JSON.stringify(value)})\`)
  }
  return value
}`,
        `function requireSessionId(value) {
  if (!value) fail('PROTOCOL_SESSION_ID_INVALID', 'sessionId is required')
  return value
}`],
      [`  CHECK (length(session_id) BETWEEN 1 AND 256),
  CHECK (session_id NOT GLOB '*[^0-9A-Za-z_-]*'),
  CHECK (session_id NOT GLOB '-*'),
`, ''],
    ],
  },
  {
    name: 'unpinned-indexes',
    claim: 'the hot statements pin their index instead of trusting planner statistics',
    edits: [
      [' INDEXED BY protocol_messages_pending_fifo', ''],
      [' INDEXED BY protocol_messages_history', ''],
      [' INDEXED BY protocol_messages_idempotency', ''],
    ],
  },
  {
    name: 'string-body-accepted',
    claim: 'the body is opaque bytes; the protocol never picks an encoding for the producer',
    edits: [[
      `  if (!(input.body instanceof Uint8Array)) {
    fail('PROTOCOL_MESSAGE_INVALID', 'body must be a Uint8Array; encode strings before enqueue')
  }
  const body = Buffer.from(input.body)`,
      `  const body = typeof input.body === 'string' ? Buffer.from(input.body, 'utf8') : Buffer.from(input.body ?? [])`,
    ]],
  },
  {
    name: 'recursive-parent-mkdir',
    claim: 'a misspelled path must not grow a plausible database tree',
    edits: [
      [`  let stat
  try {
    stat = statSync(parent)
  } catch (error) {
    fail('PROTOCOL_PATH_PARENT_MISSING', \`database parent directory does not exist: \${parent}\`, error)
  }
  if (!stat.isDirectory()) fail('PROTOCOL_PATH_PARENT_MISSING', \`database parent is not a directory: \${parent}\`)`,
        `  mkdirSync(parent, { recursive: true })`],
      [`import { statSync } from 'node:fs'`, `import { mkdirSync } from 'node:fs'`],
    ],
  },
  {
    name: 'converts-wal-instead-of-refusing',
    claim: 'a database left in WAL is refused; v1 has no runtime dual path and never converts',
    edits: [[
      `    const mode = db.prepare('PRAGMA journal_mode').get().journal_mode
    if (mode !== JOURNAL_MODE) {
      fail('PROTOCOL_JOURNAL_MODE_UNSUPPORTED',
        \`journal_mode is \${mode}, not \${JOURNAL_MODE}; v1 is rollback-journal only and does not convert a database\`)
    }`,
      `    let mode = db.prepare('PRAGMA journal_mode').get().journal_mode
    if (mode !== JOURNAL_MODE && !readOnly) {
      mode = db.prepare(\`PRAGMA journal_mode=\${JOURNAL_MODE}\`).get().journal_mode
    }`,
    ]],
  },
  {
    name: 'locality-detection-in-protocol-core',
    claim: 'storage locality is the adopter resolver\'s fail-closed precondition, not protocol core\'s job',
    edits: [
      [`import { statSync } from 'node:fs'`, `import { statSync, statfsSync } from 'node:fs'`],
      [`  if (!stat.isDirectory()) fail('PROTOCOL_PATH_PARENT_MISSING', \`database parent is not a directory: \${parent}\`)`,
        `  if (!stat.isDirectory()) fail('PROTOCOL_PATH_PARENT_MISSING', \`database parent is not a directory: \${parent}\`)
  try {
    if (isRejectedFilesystemType(statfsSync(parent).type)) {
      fail('PROTOCOL_PATH_UNSUPPORTED_FILESYSTEM', \`network filesystem: \${parent}\`)
    }
  } catch (error) { if (error instanceof ProtocolError) throw error }`],
      [`export function isSupportedSqliteVersion(version) {`,
        `export const NETWORK_FILESYSTEM_TYPES = [{ name: 'NFS', type: 0x6969 }]
export const isRejectedFilesystemType = type => NETWORK_FILESYSTEM_TYPES.some(e => e.type === type)

export function isSupportedSqliteVersion(version) {`],
    ],
  },
]

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const flip of FLIPS) {
    const banner = `// DELIBERATELY WRONG -- generated by stubs/build.mjs, do not edit and do not import from
// anything but the conformance vectors.
// Flip: ${flip.name}
// Frozen claim it violates: ${flip.claim}
// This file differs from engine.mjs in exactly ${flip.edits.length} place(s).
`
    const path = join(here, `${flip.name}.mjs`)
    writeFileSync(path, banner + apply(source, flip.edits))
    console.log(`wrote ${path}`)
  }
}
