import { createHash } from 'node:crypto'

import { fail } from './errors.js'
import type { MessageInput } from './index.js'

interface CanonicalMessage {
  protocolVersion: number
  targetSessionId: string
  senderSessionId?: string | null
  kind: string
  headers?: Record<string, string>
  body: Uint8Array
}

export interface NormalizedMessage {
  protocolVersion: number
  targetSessionId: string
  senderSessionId: string | null
  kind: string
  headers: Record<string, string>
  headersJson: string
  body: Uint8Array
  idempotencyKey: string | null
  hash: Uint8Array
}

export const PROTOCOL_VERSION = 1

export const LIMITS = {
  sessionId: 256,
  messageKind: 64,
  idempotencyKey: 256,
  headerKey: 64,
  headerValueBytes: 4096,
  headerCount: 64,
  headersJsonBytes: 65536,
  bodyBytes: 1048576,
} as const

const SESSION_ID_RE = /^[0-9A-Za-z_][0-9A-Za-z_-]*$/
const KIND_RE = /^[0-9A-Za-z._-]+$/
const HEADER_KEY_RE = /^[0-9A-Za-z._-]+$/

const u32 = (value: number): Buffer => {
  const bytes = Buffer.alloc(4)
  bytes.writeUInt32BE(value)
  return bytes
}

const u64 = (value: number): Buffer => {
  const bytes = Buffer.alloc(8)
  bytes.writeBigUInt64BE(BigInt(value))
  return bytes
}

const field = (value: string): Buffer => {
  const bytes = Buffer.from(value, 'utf8')
  return Buffer.concat([u32(bytes.length), bytes])
}

const optionalField = (value: string | null | undefined): Buffer =>
  value === null || value === undefined
    ? Buffer.from([0])
    : Buffer.concat([Buffer.from([1]), field(value)])

const sortedHeaderKeys = (headers: Record<string, string>): string[] =>
  Object.keys(headers).sort((left, right) =>
    Buffer.compare(Buffer.from(left, 'utf8'), Buffer.from(right, 'utf8')),
  )

export function canonicalPreimage(message: CanonicalMessage): Uint8Array {
  const headers = message.headers ?? {}
  const keys = sortedHeaderKeys(headers)
  const body = Buffer.from(message.body)
  return Buffer.concat([
    u32(message.protocolVersion),
    field(message.targetSessionId),
    optionalField(message.senderSessionId ?? null),
    field(message.kind),
    u32(keys.length),
    ...keys.flatMap(key => [field(key), field(headers[key])]),
    u64(body.length),
    body,
  ])
}

export function payloadHash(message: CanonicalMessage): Uint8Array {
  return createHash('sha256').update(canonicalPreimage(message)).digest()
}

export function requireSessionId(value: unknown, label = 'sessionId'): string {
  if (typeof value !== 'string') fail('PROTOCOL_SESSION_ID_INVALID', `${label} must be a string`)
  if (value.length < 1 || value.length > LIMITS.sessionId) {
    fail('PROTOCOL_SESSION_ID_INVALID', `${label} must be 1..${LIMITS.sessionId} characters`)
  }
  if (!SESSION_ID_RE.test(value)) {
    fail(
      'PROTOCOL_SESSION_ID_INVALID',
      `${label} must match [0-9A-Za-z_][0-9A-Za-z_-]* (got ${JSON.stringify(value)})`,
    )
  }
  return value
}

export function normalizeMessage(targetSessionId: string, input: MessageInput): NormalizedMessage {
  if (!input || typeof input !== 'object') fail('PROTOCOL_MESSAGE_INVALID', 'message must be an object')
  const record = input as MessageInput & Record<string, unknown>
  if ('messageId' in record) {
    fail('PROTOCOL_MESSAGE_INVALID', 'messageId is generated by the protocol; producers must not supply one')
  }
  if ('targetSessionId' in record && record.targetSessionId !== targetSessionId) {
    fail('PROTOCOL_MESSAGE_INVALID', 'targetSessionId must equal the enqueue address')
  }

  const protocolVersion = input.protocolVersion ?? PROTOCOL_VERSION
  if (!Number.isInteger(protocolVersion) || protocolVersion < 1 || protocolVersion > 0xffffffff) {
    fail('PROTOCOL_MESSAGE_INVALID', 'protocolVersion must be a positive unsigned 32-bit integer')
  }

  const kind = input.kind
  if (
    typeof kind !== 'string'
    || kind.length < 1
    || kind.length > LIMITS.messageKind
    || !KIND_RE.test(kind)
  ) {
    fail('PROTOCOL_MESSAGE_INVALID', `kind must match [0-9A-Za-z._-]{1,${LIMITS.messageKind}}`)
  }

  if (!(input.body instanceof Uint8Array)) {
    fail('PROTOCOL_MESSAGE_INVALID', 'body must be a Uint8Array; encode strings before enqueue')
  }
  const body = Buffer.from(input.body)
  if (body.length > LIMITS.bodyBytes) {
    fail('PROTOCOL_MESSAGE_INVALID', `body exceeds ${LIMITS.bodyBytes} bytes`)
  }

  const senderSessionId = input.senderSessionId ?? null
  if (senderSessionId !== null) requireSessionId(senderSessionId, 'senderSessionId')

  const idempotencyKey = input.idempotencyKey ?? null
  if (
    idempotencyKey !== null
    && (
      typeof idempotencyKey !== 'string'
      || idempotencyKey.length < 1
      || idempotencyKey.length > LIMITS.idempotencyKey
    )
  ) {
    fail('PROTOCOL_MESSAGE_INVALID', `idempotencyKey must be 1..${LIMITS.idempotencyKey} characters`)
  }

  const headersInput = input.headers ?? {}
  const headerPrototype = typeof headersInput === 'object' && headersInput !== null
    ? Object.getPrototypeOf(headersInput)
    : undefined
  if (
    typeof headersInput !== 'object'
    || headersInput === null
    || Array.isArray(headersInput)
    || (headerPrototype !== Object.prototype && headerPrototype !== null)
  ) {
    fail('PROTOCOL_MESSAGE_INVALID', 'headers must be a plain object')
  }

  const keys = Object.keys(headersInput)
  if (keys.length > LIMITS.headerCount) {
    fail('PROTOCOL_MESSAGE_INVALID', `at most ${LIMITS.headerCount} headers are allowed`)
  }
  for (const key of keys) {
    if (key.length < 1 || key.length > LIMITS.headerKey || !HEADER_KEY_RE.test(key)) {
      fail(
        'PROTOCOL_MESSAGE_INVALID',
        `header key must match [0-9A-Za-z._-]{1,${LIMITS.headerKey}} (got ${JSON.stringify(key)})`,
      )
    }
    const value = headersInput[key]
    if (typeof value !== 'string') fail('PROTOCOL_MESSAGE_INVALID', `header ${key} must be a string`)
    if (Buffer.byteLength(value, 'utf8') > LIMITS.headerValueBytes) {
      fail('PROTOCOL_MESSAGE_INVALID', `header ${key} exceeds ${LIMITS.headerValueBytes} bytes`)
    }
  }

  const headers = Object.fromEntries(sortedHeaderKeys(headersInput).map(key => [key, headersInput[key]]))
  const headersJson = JSON.stringify(headers)
  if (Buffer.byteLength(headersJson, 'utf8') > LIMITS.headersJsonBytes) {
    fail('PROTOCOL_MESSAGE_INVALID', `headers exceed ${LIMITS.headersJsonBytes} bytes`)
  }

  const envelope = { protocolVersion, targetSessionId, senderSessionId, kind, headers, body }
  return {
    ...envelope,
    idempotencyKey,
    headersJson,
    hash: payloadHash(envelope),
  }
}
