export type ProtocolErrorCode =
  | 'PROTOCOL_PATH_NOT_ABSOLUTE'
  | 'PROTOCOL_PATH_INVALID'
  | 'PROTOCOL_PATH_PARENT_MISSING'
  | 'PROTOCOL_SQLITE_VERSION_UNSUPPORTED'
  | 'PROTOCOL_JOURNAL_MODE_UNSUPPORTED'
  | 'PROTOCOL_PRAGMA_UNSUPPORTED'
  | 'PROTOCOL_SCHEMA_CHECKSUM_MISMATCH'
  | 'PROTOCOL_SCHEMA_GENERATION_UNSUPPORTED'
  | 'PROTOCOL_SCHEMA_REGISTRY_INCONSISTENT'
  | 'PROTOCOL_SESSION_ID_INVALID'
  | 'PROTOCOL_SESSION_UNKNOWN'
  | 'PROTOCOL_SESSION_RETIRED'
  | 'PROTOCOL_RETIRE_NON_EMPTY'
  | 'PROTOCOL_IDEMPOTENCY_CONFLICT'
  | 'PROTOCOL_MESSAGE_INVALID'
  | 'PROTOCOL_CURSOR_INVALID'
  | 'PROTOCOL_TRANSACTION_INVALID'
  | 'PROTOCOL_DATABASE_BUSY'
  | 'PROTOCOL_DATABASE_READONLY'
  | 'PROTOCOL_DATABASE_UNAVAILABLE'
  | 'PROTOCOL_DATABASE_CORRUPT'
  | 'PROTOCOL_SQLITE_ERROR'

export class ProtocolError extends Error {
  readonly code: ProtocolErrorCode

  constructor(code: ProtocolErrorCode, message: string, cause?: unknown) {
    super(message, { cause })
    this.name = 'ProtocolError'
    this.code = code
  }
}
