import { execFileSync } from 'node:child_process'
import { basename, dirname } from 'node:path'

export interface ChangeReportOptions { repoRoot: string; rev?: string; range?: string; note?: string; maxHunkLines?: number; parentSessionId?: string }
const run = (root: string, args: string[]): string => execFileSync('git', ['-C', root, ...args], { encoding: 'utf8' })
const nodeId = (path: string): string => basename(dirname(path))
const parseFm = (source: string): Record<string, string[]> => { const out: Record<string, string[]> = {}; const match = source.match(/^---\n([\s\S]*?)\n---/); if (!match) return out; let key = ''; for (const line of match[1].split('\n')) { const item = line.match(/^\s*-\s+(.*)$/); if (item && key) (out[key] ??= []).push(item[1].trim()); else { const at = line.indexOf(':'); if (at > 0) { key = line.slice(0, at).trim(); out[key] = line.slice(at + 1).trim() ? [line.slice(at + 1).trim()] : [] } } } return out }
export function buildChangeReport(options: ChangeReportOptions): string {
  const root = options.repoRoot; const tip = options.rev ?? (options.range ? options.range.split('..').at(-1) : 'HEAD') ?? 'HEAD'; const base = options.range ? options.range.split('..')[0] : `${tip}^`; const sha = run(root, ['rev-parse', tip]).trim(); const changed = run(root, ['diff', '--name-status', '-M', `${base}..${tip}`]).trim().split('\n').filter(Boolean).map(line => { const parts = line.split('\t'); return { status: parts[0], path: parts.at(-1)! } }); const specFiles = changed.filter(file => file.path.endsWith('/spec.md')); const nonSpec = changed.filter(file => !file.path.endsWith('/spec.md')); const onlyAck = specFiles.length === 0 && nonSpec.length > 0 && nonSpec.every(file => /evals\.ndjson|ack/i.test(file.path)); const lines = [`spec change report ${sha}`]
  if (onlyAck) lines.push('仅 ack/eval，正文未变 (empty=true)')
  else { const limit = Math.max(0, options.maxHunkLines ?? 40); for (const file of specFiles.sort((a, b) => a.path.localeCompare(b.path))) { const fm = parseFm(run(root, ['show', `${tip}:${file.path}`])); lines.push(`\n${nodeId(file.path)} — ${fm.desc?.[0] ?? ''}`); const diff = run(root, ['diff', '--unified=0', `${base}..${tip}`, '--', file.path]); const fmChanges = diff.split('\n').filter(line => /^[+-](?:code|related|status):|^[+-]\s+-\s+/.test(line) && /code|related|status/.test(line)); lines.push(`status: ${file.status}${fmChanges.length ? `; frontmatter: ${fmChanges.join(' | ')}` : ''}`); const body = diff.split('\n').filter(line => /^@@|^[+-](?![+-])/.test(line) && !/^---|^\+\+\+/.test(line)).filter(line => !/^@@/.test(line)); if (body.length) { lines.push('body:'); lines.push(...body.slice(0, limit)); if (body.length > limit) lines.push(`... (more in git show ${sha}:${file.path})`) } } }
  for (const row of run(root, ['diff', '--numstat', '-M', `${base}..${tip}`]).trim().split('\n').filter(Boolean)) { const [add, del, path] = row.split('\t'); if (!path || path.endsWith('/spec.md')) continue; lines.push(`文件 ${path} (+${add === '-' ? 0 : Number(add)} −${del === '-' ? 0 : Number(del)})，由节点 ${ownersFor(path, root, tip) || '未声明'} 治理`) }
  lines.push(`\n${options.note ?? '发送者未说明原因'}`); lines.push(`父 session ${options.parentSessionId ?? '未提供'} 在 ${sha} 改了以上节点，你依赖的契约可能已变；做完手头这一步后重读它们，需要返工就返工，有异议用 spex session send ${options.parentSessionId ?? '<parent>'} 回我。这是请求不是命令。`); return lines.join('\n')
}
function ownersFor(path: string, root: string, tip: string): string { for (const specPath of run(root, ['ls-tree', '-r', '--name-only', tip, '--', '.spec']).split('\n').filter(path => path.endsWith('/spec.md'))) { if ((parseFm(run(root, ['show', `${tip}:${specPath}`])).code ?? []).some(claim => claim.split('#')[0] === path)) return nodeId(specPath) } return '' }
