// GENERATED by scripts/gen-migrate-table.mjs — do not hand-edit. See [[migrate]].
// For each plugin asset the shipped templates still carry: every git blob sha its OLD-WORLD (.config-era)
// content ever had on main. `spex doctor --migrate` hashes an adopter's file; a hit on oldShas means the
// file is a stock historical template → safe to replace wholesale with the shipped template. Anything
// else is flagged for review, never rewritten.
export type MigrateAsset = { rel: string; template: string; oldShas: string[] }
export const TEMPLATE_ASSETS: MigrateAsset[] = [
  {
    "rel": "clarify-before-code/spec.md",
    "template": "templates/presets/careful/.plugins/clarify-before-code/spec.md",
    "oldShas": [
      "a1b9c7e189df9b75a27005d381b43682d717ee6f"
    ]
  },
  {
    "rel": "core/idle/idle.sh",
    "template": "templates/spec/project/.plugins/core/idle/idle.sh",
    "oldShas": [
      "21abdf5593bf2f73823cff9afe079ce79a8f3d2b",
      "2de24b434d53e281e60dc1a57b62536df2f8e528",
      "69653eb23b7b9791c14ab263d77d5989102095cb",
      "c4c13a4dbc6543eb39e766de11be89cd247a251d"
    ]
  },
  {
    "rel": "core/idle/spec.md",
    "template": "templates/spec/project/.plugins/core/idle/spec.md",
    "oldShas": [
      "1283e0c3be0db754fdf88b6e939f727bbb990a03",
      "52f84eb9c7d60c6058a3e9e3f0b410a272ec3bf2",
      "eb31ed98313cf0ede3f863f8f8da1e1c70d3cc6e"
    ]
  },
  {
    "rel": "core/mark-active/mark-active.sh",
    "template": "templates/spec/project/.plugins/core/mark-active/mark-active.sh",
    "oldShas": [
      "0e4836f0dc0bf9f7878631040bc0848f665e7655",
      "61cc56baea4ba77e2bd0861f436c7860f68e580f",
      "c3276b87ff15d47886e92ed0e6710ce60c25cfef"
    ]
  },
  {
    "rel": "core/mark-active/spec.md",
    "template": "templates/spec/project/.plugins/core/mark-active/spec.md",
    "oldShas": [
      "55a76108cfa749dc022b9566c77a69acbde96892",
      "6469e1d31f41e49774e148416aca1b69bf105a5c"
    ]
  },
  {
    "rel": "core/session-fail/fail.sh",
    "template": "templates/spec/project/.plugins/core/session-fail/fail.sh",
    "oldShas": [
      "54b6b4a10265063ae7e1306f4aaeba7a5f878181",
      "61da557a1a370edda0c13702abd587fa3406cf29",
      "7c9d7e7243038cc0ab904c821cf3adbc719e23fb",
      "f7ce6d9063557d27c253f62defced643bd86529b"
    ]
  },
  {
    "rel": "core/session-fail/spec.md",
    "template": "templates/spec/project/.plugins/core/session-fail/spec.md",
    "oldShas": [
      "0877dbe2f94ed8fcf5ded09b48e9705e9427ffad",
      "41fbbaf512d6074a89720f2d2081059ece3c0ef1",
      "ff25265b87144b16f4101f302206800bd6505d72"
    ]
  },
  {
    "rel": "core/spec-first/spec-first.sh",
    "template": "templates/spec/project/.plugins/core/spec-first/spec-first.sh",
    "oldShas": [
      "98f0448bf625ed57bfbb108183b7f5dc9ff227d4",
      "a9776998b7c7b2b196a34569f9c231c9fd4bdc6a",
      "b346120241f8933684ef6d4708cc3b94b8ff9f15",
      "c55e3e0b6d1c84aed988d073bd07faf9b190ef83",
      "c93a29b487d998f3c039c3e71bdb9ae52acd3d4b",
      "ee13a95cd412c5b6518ed1e486c1642867068bc4"
    ]
  },
  {
    "rel": "core/spec-first/spec.md",
    "template": "templates/spec/project/.plugins/core/spec-first/spec.md",
    "oldShas": [
      "3b4deed2d004bbc30443b2faa7cf94d2e9892c77",
      "44b6c83ce4091fc4903a917cfb8f275477323404"
    ]
  },
  {
    "rel": "core/spec-of-file/spec-of-file.sh",
    "template": "templates/spec/project/.plugins/core/spec-of-file/spec-of-file.sh",
    "oldShas": [
      "29684a87e418e0a0af331ed2e1ac04463726eb4d",
      "6afc41d97fef1feb18bb46e9e32ca787197bc6b5",
      "7b466977a3564e2642fa70ed17cd4250f27f8127",
      "7d6650063592ea1825c3abfd765f075dbe953e16",
      "b58f65e59c5dc050e642689082a666a74efea51c",
      "bc22dc7593214e52309a6747d4a9a3d8755b6adc",
      "d8cbc4f7a7e3090219e7a6cbdc0b9462557cb18e",
      "f70627ea80f9afb1312de97154b8b2457a34ab46"
    ]
  },
  {
    "rel": "core/spec-of-file/spec.md",
    "template": "templates/spec/project/.plugins/core/spec-of-file/spec.md",
    "oldShas": [
      "5fbf9f0ecc3c8ec7d76f9e3d4a06c3aad5e7c92b",
      "657428043cc46fe5a94382681b9e00f52a740a5a",
      "76c035dfb8add59282018a582e1827a9fae68672"
    ]
  },
  {
    "rel": "core/spec.md",
    "template": "templates/spec/project/.plugins/core/spec.md",
    "oldShas": [
      "0c04edb308902a768a290586e2af8be779fef2e9",
      "1e422538d16ae7995480542e65606d7ffafe1cbc",
      "21f618f2d0739d6d9d7cb5c9fcafa1d4e952b98f",
      "27d18a5cf05c76c5526829e655401bd67e81df04",
      "2bd4ec88fc9fc314e9a564754ffcc4ab0f24b72d",
      "443bf1445175fe5c5ae987296e80a2bab8dd99b0",
      "773167e6ccf73bbe7dad2e787c10089710a5ce5d",
      "7a5c8b1c66dc5a4718ef9c76f65ea793aa7dcbf7",
      "8a90a6bd9b0046ef7224baad9c7311585639d779",
      "935a491939b8d5d4351f38392c3fda0699b3b996",
      "c312de5047c7c4f34864e7073890ed677440f9a5",
      "e576625e783dba3846ca147193e36c6f4b3f45e9",
      "e5ba73eae889f4943bb3cd8a99e07323492de654",
      "f7737174c9c046faaf5968ed0ef3e033732f4d64",
      "f799e80bd590757b2523a53eda2d28336272a0bb"
    ]
  },
  {
    "rel": "core/stop-gate/spec.md",
    "template": "templates/spec/project/.plugins/core/stop-gate/spec.md",
    "oldShas": [
      "16eb95ec994dd2fa4eb3e2a8bd3c2387145876fc",
      "5507a7c09160b4eee24526273ffdfb5e12ecc179",
      "9c98d048863d5a7da650ad42735948e875ab20b5",
      "b8237ed34fc04a38629bb940c75bc07f48b18e52",
      "e1042c6dc55e502fbb0bcecb583c56bcf75e2909",
      "e3822eca5d899d13225f4af6e0442c87f6a66630",
      "eff5e2e88e7f907952701bb233eb8c9b18fb1874"
    ]
  },
  {
    "rel": "core/stop-gate/stop-gate.sh",
    "template": "templates/spec/project/.plugins/core/stop-gate/stop-gate.sh",
    "oldShas": [
      "1596389b23b9813955316f617b61f188319eb1e4",
      "372fe4c89780cfcfbc7aca045822661233271fe1",
      "4fb4b69e8e6cc79ad2d30f1d7da51e99563a81c1",
      "57b65e4d0c26e79edf9bba20ee838aa1cb068390",
      "5dbd53b426a650a353c97db2026c02ff9fa26e57",
      "74b2a417f58c1d592a260e718aa253b06a5f46ca",
      "7f7cf30c3beae6e1e3f487fa5fd4286ff87879fd",
      "8b7816a6fb5581249bb2157dbebe392f27453583",
      "b1ff677ca787a73638df25b23f3eaa1aa259712b",
      "eb4dc1ea4bbb7e15e4da5b4c51d2f7ddc49142e3"
    ]
  },
  {
    "rel": "distill/digest.mjs",
    "template": "templates/spec/project/.plugins/distill/digest.mjs",
    "oldShas": [
      "b596d196d35688130157698ca90950d412bf527f",
      "faff3509b004e8529d5c7f3abd29512fb389ceb9"
    ]
  },
  {
    "rel": "distill/spec.md",
    "template": "templates/spec/project/.plugins/distill/spec.md",
    "oldShas": [
      "3e3fd25db1d465f72b636e6af8bcd873c0ceb3c2",
      "4a0b547ad63e15aa80ed7f826581ad90ca02d0f4",
      "7b6cfc2a6e1e75bf96e545ff253d529b0c4f1cd7"
    ]
  },
  {
    "rel": "extract/spec.md",
    "template": "templates/spec/project/.plugins/extract/spec.md",
    "oldShas": [
      "064efd8321925bd0cff7ee725771b500a7baf6e7",
      "45c2b0fe12224ebc124b5f5fecafd1e8d82de93e",
      "4a156b77557def4e0b9cf52a3f304e62bdc5b047",
      "50dd5d5d8c9f4c4496c250852b061300e2d5af21",
      "6bcdd3fb78e73dad63b0f8edd9c9de0172ab9a73",
      "6fde1164bf71f18f83ce56645b5735e192aad569",
      "74ef28d8d9402a88d961968b1f06f4c2b331881e",
      "c7d248832bc61de440dc49152f6db9df4da7bedf",
      "d260436c3327b6a963ccb38f2ca58b37b6c73058",
      "d2ced748666713353e4bee4cbc2d68bc2b2c9028",
      "d655265260b16d77510e9fc9ef497aa757ab6fd4"
    ]
  },
  {
    "rel": "forge-link/spec.md",
    "template": "templates/spec/project/.plugins/forge-link/spec.md",
    "oldShas": [
      "2472c085e6f72364eea004ba1d1b1f8d6b4e13ac",
      "c86439c5a3fe6cb3ece2c40186da0f476d1c52d4"
    ]
  },
  {
    "rel": "memory-hygiene/spec.md",
    "template": "templates/spec/project/.plugins/memory-hygiene/spec.md",
    "oldShas": [
      "2b5313e770c7d2e857817adcf7bb72aecaeca45f"
    ]
  },
  {
    "rel": "regroup/spec.md",
    "template": "templates/spec/project/.plugins/regroup/spec.md",
    "oldShas": [
      "37f632450faba3e9c5290468b52535e766faf45e",
      "aa3097a1b7ff51c4a8a0bfab82ac06a585081caa",
      "b4e8d4339447eaaf61e9b3511822ba04711687a2"
    ]
  },
  {
    "rel": "reproduce-before-fix/spec.md",
    "template": "templates/spec/project/.plugins/reproduce-before-fix/spec.md",
    "oldShas": [
      "28eef30893a83b634900e43dfe729043c8f60ea8",
      "2d056b7344cbc0c4eb0dbeb0ba69ccee0e8b47db",
      "83705fa143980f0b01ccafdd033c7777fd98f886",
      "cb5495db2cc4ba34251ddd47b1b56a18186b8bab",
      "fc3c060af70b01b2073163880a42d002e285ddc5"
    ]
  },
  {
    "rel": "spec.md",
    "template": "templates/spec/project/.plugins/spec.md",
    "oldShas": [
      "602a96c9c68d1884fd2c59796b0fd3acc167339c",
      "6421338ed214faba621b37f0ceb0b7cb45d4982d",
      "6e47647fed183564e67da4d6fa825a567252d266",
      "6fe57805ab5367eb164ace1ddb942686a3e4c190",
      "7af216894d2b2b27b8894bea3428bcf773cfd254",
      "9f26906c7fcd7746b063a8c015a14502215ad548",
      "a27ab437b3634219d89ef91e95cbb7fb7fd9b569",
      "c9a789462fb0710c7e081d3eb155981679ec52af",
      "cc65afacb6ffc3d7f09893b29b5f9d3567659c3e",
      "e6f2659001b9a28796c7c4f059c4a68598f883f0",
      "eecc63a06403ef770bc4317d9f419b7a87a93a30",
      "fc35275b30cdcadf57e8117318619066a31acc97"
    ]
  },
  {
    "rel": "supervisor/spec.md",
    "template": "templates/spec/project/.plugins/supervisor/spec.md",
    "oldShas": [
      "036d5602a038e2565cd968e4a8a443ce80026025",
      "05963c00bc1031ba0d4f91ea68d60b1731f475f2",
      "0b73cd94b7c383d8bc0c0b7732f0ac0fb6f043ec",
      "138401178dc2a6af43e2fe3c8764492e22ae18a8",
      "19235140c66dcd4596df6934b58b676d6cd5e4dc",
      "446e630937320c5a113a5b13a1744b097cb1cbec",
      "52a9244e01d97ab7492d5f6763f6cb05290204ee",
      "5630799b96b0aa121c3f903ea2363ed15e4f0522",
      "7d8b335dae833b19435c0ae161472b2096f395e0",
      "8ac7ed6a22276356f8c9e67148d1b3b42a907923",
      "ac703be505c05866697db125629a818b71789452",
      "c36152b38e61ac963381ae340fc0b3249459eec1",
      "cd26d2d8682755101b893f95767726edbe17020f",
      "decb8704259e091e53bd86dcde0c8f0a585a32cd",
      "fc24e7e073286c4e4456e8ac1a57ece5096a848f",
      "fe7b7be5eb4015701a62666e8943fa1165d813cf"
    ]
  },
  {
    "rel": "tidy/spec.md",
    "template": "templates/spec/project/.plugins/tidy/spec.md",
    "oldShas": [
      "096fc1dd48a1692aeb87614a93bcce2473f2050a",
      "16ccbf044e74765a5c9cc212fba38356950a7e69",
      "25e20082d9f5ccb3b307b707511aaa5daa2d9aea",
      "5bf288a06976646610ffab474b73f80b3910dc14",
      "69338dc687e086a79767caedc2d76c38c6fc8ed5",
      "b982b1781628c8692692d808713e99e4041737ab",
      "d0e7144d60ab5dfce5475fdd3973a2c4a38240a3",
      "e26a030b817e739ffaa92eb1002b4fb57cae2c15"
    ]
  }
]
// old-world template assets the shipped package no longer carries (recognized → reported, not replaced):
export const RETIRED_ASSETS: Record<string, string[]> = {
  "core/harness-session-id/harness-session-id.sh": [
    "32b3b963ba6c2c659f0543e82a2a34128c4860bf",
    "626d7f3c56d6430c5dafb7713880a606b4ee8b03"
  ],
  "core/harness-session-id/spec.md": [
    "196aefe5cc0d0529b70909fc0739795c969d7f97",
    "9377704426e14274fafb9a17584d21f6de4b24c3",
    "c05f182fc92fcd224f4c7953dc118e59665971aa",
    "c617fc05780f921c55280b68d9f55e60110f74eb"
  ],
  "core/stop-gate/yatsu.evals.ndjson": [
    "268c06c27f3b2dc71da8c0aca4d0507a227829f9",
    "e681fe71b8519577c19bb4f13bc0f310fb92dc31"
  ],
  "core/stop-gate/yatsu.md": [
    "f83f6b2406eb359beb1181bf0145558241806116"
  ],
  "e2e-review/spec.md": [
    "4aaad498f958f64f0146d386a71d48d0f25f6cf5",
    "f24d227243dccc3f1136a110d24be32e527123f5",
    "f4a98ba8a15a809855bafa3a0073078c00e63755"
  ],
  "e2e-review/split-recordings.mjs": [
    "560502edf6534944789065dce5ad137a5c70a83d",
    "ab210ac57cd89b239175f1380ef833d1db36bd71"
  ],
  "health/spec.md": [
    "73f077df5b1a159733ad04eb080f1f8e99c7312f",
    "79a23352c10f29ed8df0cc70752f6af531f2329c",
    "866953002c6da44026fb920ee5e1057a3b988498"
  ],
  "ritual/spec.md": [
    "3fe416cf6207742a40894eeae32e3e52ddc03062",
    "5decceeed6a0da3b1eb1c6ab62fc2411a702af64",
    "6ec1d39979c4769c27abafc456a677baf510cd89"
  ],
  "sanity-check/spec.md": [
    "02d2356e2501f3c07252832485f0b4a7f925ed83"
  ],
  "scenario/spec.md": [
    "753711df483af9361fea50359cf2d4ba65f7ccdb",
    "76dcc35b3f836125c89abfb9631982fed846a811",
    "78cbf9a3101a2a5f435bfbaaa9afc74e04912ccb"
  ],
  "search-first/spec.md": [
    "285fcfbb300a4cb58270d4c35a485b39fe30f9c9"
  ],
  "slash/health/spec.md": [
    "718af0b53796943fe7406caad537a00480e1d6dd"
  ],
  "slash/tidy/spec.md": [
    "bd7a43c097234678224b3a2082def5a245ee169d"
  ],
  "spec-scout/spec.md": [
    "25421b7d025231b1401db7823b74d4022ac8967e",
    "bba79ba76ac8ec3b60ef6e1f7b0ace051c39b7a0"
  ],
  "system/core/spec.md": [
    "e5a9ff542750630f88e6a76fd1038da17d0909dd"
  ],
  "system/ritual/spec.md": [
    "96582cef3b299ac251dee9e56b4343315058aafa"
  ],
  "system/voice-before-ask/setup.sh": [
    "83b36886afa446ed25bbce2ceece195398f52057"
  ],
  "system/voice-before-ask/spec.md": [
    "a075f3b392f66f355382483bf421dec30af15555"
  ],
  "taste/campaign-framework.md": [
    "552807ea784d8dba18aa8308cfb1c8016515b727",
    "cf57d39f8a9537b00e9d4595659be77bd625b0d5"
  ],
  "taste/campaign-issues.md": [
    "f12e257f8c4f3128d33f83f86614f3c276cd88eb"
  ],
  "taste/campaign-simplifications.md": [
    "4ec551ccaf3c9f25a4ffac4edc92b907ddca739c"
  ],
  "taste/spec.md": [
    "10b3b4e8538406168de9b7f92ca9790aadb855b3",
    "9cd4ac0aac1492fb7a9dde1e51bc3884e4ae5a2c",
    "a17da863f8c4d5771d3eeb554b2e989c47e7cef1",
    "e268f9c5d5321e5d0b371d4e2e9a23a56fa639c9"
  ],
  "taste/ten-challenges.html": [
    "94a6aaa3ec39471277ba9701439f2291005a5f06"
  ],
  "voice-before-ask/setup.sh": [
    "83b36886afa446ed25bbce2ceece195398f52057"
  ],
  "voice-before-ask/spec.md": [
    "03300cf5f1c8472a739921000c51b5c0f26dcc64",
    "0b12287e94728b320cc89a41ff7d822ba17af6b2",
    "0bf33cc9a6dc8d39d4721a333d510b3700218720"
  ]
}
// every historical blob of spexcode's own `config` node spec.md (the plugin-system spec, pre-rename) —
// gates the config→plugin-system node rename on adopter trees:
export const CONFIG_NODE_SHAS: string[] = [
  "347eeeec0324304a5fabfba7c28b815a41dd0962",
  "3e4f7bc85511702cfe5bf49f162944eebace3c2e",
  "5bfbcddfb91acb1fb0160e3d9234783922c85166",
  "8cabe11fe87e536b14e99e4f869b850bd4eb236b",
  "a55b18611fd12a42c8fccd4f4d0bf34c7db83ccb",
  "c632732d182465ec03c1a2cff1e1b9a2a9faaee2",
  "ccada063410660cff034b015fd1bb3e4bf5eac67",
  "ee45ca053e0f29bf5ab236d11518a87ec961db3e"
]
