import { shimRuntimeSource } from './shim-runtime.js'

// @@@ opencode plugin generator - the opencode adapter's "shim" is not a settings JSON but a generated
// opencode PLUGIN (.opencode/plugins/spexcode.ts, auto-loaded by opencode from the project tree) that runs
// inside the agent process. It is a THIN HOST over the shared shim runtime ([[shim-runtime]], embedded
// verbatim): this generator declares opencode's event-bus mapping (session.created → SessionStart,
// chat.message → UserPromptSubmit, tool.execute.before/after → Pre/PostToolUse, session.idle → Stop) and its
// host bindings; the payload synthesis, the block verdict (exit 2 + stdout decision:block JSON), and the
// rendezvous server come from the runtime. opencode's host-specific verdict consumers ([[opencode-harness]]):
// a PreToolUse block THROWS (opencode aborts the tool call); a Stop block re-injects the gate's reason as a
// follow-up prompt via the SDK client, closing the stop-gate loop. What re-enters is always the parsed
// REASON, never the escaped wire JSON. The rendezvous inject is client.session.prompt into the ROOT session,
// gated by canInject (a plugin with no adopted session reply-rejects instead of confirming an undeliverable
// prompt). What genuinely stays opencode-only below: session tracking (root vs subagent children, the
// agent_id stamp), the minted-id capture, and the two resume seeds.
// This module is a PURE content producer (no imports from harness.ts — the adapter object lives there, in the
// one HARNESSES seam) so there is no import cycle.

// the lifecycle events the generated plugin can emit (drives the shim + hooks-manifest binding). opencode's
// bus has no failed-stop and no idle/attention notification event, so StopFailure/Notification are genuinely
// absent — the same five codex binds.
export const OPENCODE_EVENTS = ['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PostToolUse', 'Stop'] as const

// opencode tool name → Claude tool name, so [[inject-spec-first]] / [[inject-spec-of-file]] and every other
// claude-family handler read the payload with zero opencode knowledge. Unknown tools pass through untouched
// (opencode's names are lowercase). Exported for tests.
export const OPENCODE_TOOL_NAMES: Record<string, string> = {
  bash: 'Bash', edit: 'Edit', write: 'Write', read: 'Read', grep: 'Grep', glob: 'Glob', list: 'LS',
  patch: 'Edit', todowrite: 'TodoWrite', todoread: 'TodoRead', webfetch: 'WebFetch', task: 'Task',
}

// the generated plugin source. `dispatch` and `spex` are absolute paths baked at materialize time (same as
// every shim); the 'dispatch.sh' substring doubles as the identity stamp cleanHarness gates removal on. The
// file is plain TS with no @opencode-ai/plugin type import, so it loads regardless of the host project's
// node_modules; opencode calls every exported function with its plugin context.
export function opencodePluginSource(dispatch: string, spex: string): string {
  return `// spexcode: GENERATED by spex materialize — do not edit (regenerated per clone; see [[opencode-harness]])
// Bridges opencode's event bus into SpexCode's dispatch.sh (claude-shaped payloads) and serves the
// per-session rendezvous socket for prompt delivery + liveness.
import { spawn } from "node:child_process"
${shimRuntimeSource('opencode', dispatch, spex)}

const TOOL_NAMES = ${JSON.stringify(OPENCODE_TOOL_NAMES)}

export const SpexcodePlugin = async (ctx) => {
  const client = ctx && ctx.client
  const cwd = (ctx && (ctx.directory || (ctx.app && ctx.app.path && ctx.app.path.cwd))) || process.cwd()
  const recordId = (process.env.SPEXCODE_SESSION_ID || "").trim()
  const rt = spexShimRuntime({ sessionId: () => recordId, cwd: () => cwd })

  // session tracking: the ROOT opencode session is this worker's conversation; child sessions (subagents)
  // are stamped agent_id so a parent's declared state stays out of its subagents' reach (the same
  // discriminator claude's Task subagents carry). A RESUMED session re-fires no bus event until poked, so
  // event-driven adoption alone leaves a resumed worker unreachable (the daemon reply-rejects every
  // delivery): a --session resume seeds rootSession from the launch env (the resume marker's id), and a
  // --continue resume falls back to asking the SDK for the newest root session.
  let rootSession = (process.env.SPEXCODE_OPENCODE_RESUME_ID || "").trim()
  const children = new Set()
  const stamp = (sid) => (sid && children.has(sid) ? { agent_id: sid } : {})
  // opencode MINTS its own session id — report it once so the backend stores it as harness_session_id
  // (what reopen() resumes with, \`--session <id>\`). Fire-and-forget; a failure only costs resume-by-id.
  let captured = !!rootSession   // a seeded (resumed) id is already on the record — don't re-report it
  const capture = (sid) => {
    if (captured || !sid || !recordId) return
    captured = true
    try { spawn(SPEX, ["internal", "opencode-capture", sid], { cwd, env: process.env, stdio: "ignore" }) } catch { /* resume falls back to --continue */ }
  }
  const adopt = (sid) => { if (!rootSession && sid) { rootSession = sid; capture(sid) } }
  const injectPrompt = async (text) => {
    if (!client || !rootSession) throw new Error("no session to prompt")
    await client.session.prompt({ path: { id: rootSession }, body: { parts: [{ type: "text", text }] } })
  }

  // --continue resume: no owned id was ever captured, and a reattached session fires no bus event until
  // poked — ask the SDK for the newest root session (what --continue itself reattached) so deliveries can
  // inject. Gated on the launch marker so a FRESH launch can never adopt a stale session; best-effort with
  // bounded retries (the server may still be loading at plugin init), shape-defensive, and adopt() ignores
  // the late result if a real event won the race.
  if (!rootSession && process.env.SPEXCODE_OPENCODE_CONTINUE && client && client.session && typeof client.session.list === "function") {
    (async () => {
      for (let i = 0; i < 10 && !rootSession; i++) {
        try {
          const res = await client.session.list()
          const arr = (res && (res.data || res)) || []
          const roots = (Array.isArray(arr) ? arr : []).filter((s) => s && s.id && !s.parentID)
          const at = (s) => (s.time && (s.time.updated || s.time.created)) || 0
          roots.sort((a, b) => at(b) - at(a))
          if (roots.length) { adopt(roots[0].id); return }
        } catch { /* not up yet — retry */ }
        await new Promise((r) => setTimeout(r, 1000))
      }
    })()
  }

  // the rendezvous daemon, from the shared runtime: {type:"reply"} injects into the root session (a plugin
  // that adopted no session yet reply-rejects synchronously, BEFORE repaint-done, so the sender fails loud
  // instead of confirming a prompt that can never inject); {type:"repaint"} answers repaint-done in the same
  // synchronous parse pass — confirmation means PARSED, not processed. The injection itself (a whole model
  // turn: the SDK prompt call resolves only when the TURN ends) runs BEHIND the confirm.
  rt.serveRendezvous(injectPrompt, { canInject: () => !!(client && rootSession) })

  const toolPayload = (input, output) => {
    const sid = (input && input.sessionID) || ""
    return {
      ...stamp(sid),   // agent_id must precede tool_input — harness.sh's hp_is_subagent prefix scan
      tool_name: TOOL_NAMES[(input && input.tool) || ""] || ((input && input.tool) || ""),
      tool_input: rt.toolInput(output && output.args, "filePath"),
    }
  }

  return {
    event: async ({ event }) => {
      const t = event && event.type
      const p = (event && event.properties) || {}
      if (t === "session.created") {
        const info = p.info || {}
        if (info.parentID) children.add(info.id)
        else if (!rootSession) { adopt(info.id); await rt.dispatchEvent("SessionStart", { source: "startup" }) }
      } else if (t === "session.idle") {
        const sid = p.sessionID || ""
        if (sid && rootSession && sid !== rootSession) return   // a subagent going idle is not this worker's Stop
        adopt(sid)
        const r = await rt.dispatchEvent("Stop", {})
        // the stop-gate loop closes in-process: the gate's parsed reason re-enters as a follow-up prompt.
        if (rt.blocked(r)) { try { await injectPrompt(rt.blockReason(r, "blocked by a spexcode hook")) } catch { /* gate reason lost; next idle re-fires it */ } }
      }
    },
    "chat.message": async (input, output) => {
      const sid = (output && output.message && output.message.sessionID) || (input && input.sessionID) || ""
      if (!(sid && children.has(sid))) adopt(sid)
      const text = ((output && output.parts) || []).filter((x) => x && x.type === "text").map((x) => x.text).join("\\n")
      await rt.dispatchEvent("UserPromptSubmit", { ...stamp(sid), prompt: text })
    },
    "tool.execute.before": async (input, output) => {
      const r = await rt.dispatchEvent("PreToolUse", toolPayload(input, output))
      if (rt.blocked(r)) throw new Error(rt.blockReason(r, "blocked by a spexcode hook"))   // aborts the tool call — the PreToolUse block contract
    },
    "tool.execute.after": async (input, output) => {
      await rt.dispatchEvent("PostToolUse", toolPayload(input, output))
    },
  }
}
`
}
