// @@@ opencode plugin generator - the opencode adapter's "shim" is not a settings JSON but a generated
// opencode PLUGIN (.opencode/plugins/spexcode.ts, auto-loaded by opencode from the project tree) that runs
// inside the agent process and plays TWO roles ([[opencode-harness]]):
//   1. hook bridge — it subscribes to opencode's event bus and re-emits each event as a Claude-SHAPED payload
//      piped into `dispatch.sh opencode <Event>` (session_id = the governed record id from the launch env,
//      Claude tool names, `file_path`), so harness.sh needs no opencode parse arm — the default (claude
//      family) branch handles it, exactly like the `plugin` bundle form. A blocking outcome is honored
//      in-process: a PreToolUse block THROWS (opencode aborts the tool call); a Stop block re-injects the
//      gate's reason as a follow-up prompt via the SDK client, closing the stop-gate loop.
//   2. rendezvous daemon — it binds SpexCode's per-session rendezvous socket (CLAUDE_BG_RENDEZVOUS_SOCK from
//      the launch env, the path every rendezvous-owning harness is handed) and answers the reply/repaint
//      mini-protocol, so the claude adapter's deliver (parse-confirmed atomic write) and socket-listener
//      liveness are reused VERBATIM — `ownsRendezvous: true` is literally true, no opencode transport code.
// This module is a PURE content producer (no imports from harness.ts — the adapter object lives there, in the
// one HARNESSES seam) so there is no import cycle.

// the lifecycle events the generated plugin can emit (drives the shim + hooks-manifest binding). opencode's
// bus has no failed-stop and no idle/attention notification event, so StopFailure/Notification are genuinely
// absent — the same five codex binds.
export const OPENCODE_EVENTS = ['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PostToolUse', 'Stop'] as const

// opencode tool name → Claude tool name, so [[inject-spec-first]] / [[inject-spec-of-file]] and every other
// claude-family handler read the payload with zero opencode knowledge. Unknown tools pass through capitalized
// (opencode's names are lowercase). Exported for tests.
export const OPENCODE_TOOL_NAMES: Record<string, string> = {
  bash: 'Bash', edit: 'Edit', write: 'Write', read: 'Read', grep: 'Grep', glob: 'Glob', list: 'LS',
  patch: 'Edit', todowrite: 'TodoWrite', todoread: 'TodoRead', webfetch: 'WebFetch', task: 'Task',
}

// the generated plugin source. `dispatch` and `spex` are absolute paths baked at materialize time (same as
// every shim); the 'dispatch.sh' substring doubles as the identity stamp cleanHarness gates removal on. The
// file is plain TS with no @opencode-ai/plugin type import, so it loads regardless of the host project's
// node_modules; opencode calls every exported function with its plugin context.
export function opencodePluginSource(dispatch: string, spex: string): string {
  return `// spexcode: GENERATED by spex materialize — do not edit (regenerated per clone; see [[opencode-harness]])
// Bridges opencode's event bus into SpexCode's dispatch.sh (claude-shaped payloads) and serves the
// per-session rendezvous socket for prompt delivery + liveness.
import { spawn } from "node:child_process"
import { createServer } from "node:net"
import { existsSync, unlinkSync } from "node:fs"

const DISPATCH = ${JSON.stringify(dispatch)}
const SPEX = ${JSON.stringify(spex)}
const TOOL_NAMES = ${JSON.stringify(OPENCODE_TOOL_NAMES)}

export const SpexcodePlugin = async (ctx) => {
  const client = ctx && ctx.client
  const cwd = (ctx && (ctx.directory || (ctx.app && ctx.app.path && ctx.app.path.cwd))) || process.cwd()
  const recordId = (process.env.SPEXCODE_SESSION_ID || "").trim()

  // feed one claude-shaped payload to dispatch.sh; the harness id "opencode" is baked as argv[1] (the
  // deterministic shell-side detector). Payload key order matters: agent_id (when present) must precede
  // tool_input so harness.sh's hp_is_subagent prefix scan can see it.
  const dispatchEvent = (event, payload) => new Promise((resolve) => {
    let out = "", err = ""
    let child
    try {
      child = spawn("bash", [DISPATCH, "opencode", event], { cwd, env: { ...process.env, SPEX }, stdio: ["pipe", "pipe", "pipe"] })
    } catch (e) { resolve({ code: 1, out, err: String(e) }); return }
    child.stdout.on("data", (d) => { out += d })
    child.stderr.on("data", (d) => { err += d })
    child.on("error", (e) => resolve({ code: 1, out, err: err || String(e) }))
    child.on("close", (code) => resolve({ code: code == null ? 1 : code, out, err }))
    child.stdin.end(JSON.stringify({ session_id: recordId, cwd, hook_event_name: event, ...payload }))
  })
  const blocked = (r) => r.code === 2 || /"decision"\\s*:\\s*"block"/.test(r.out)
  const reason = (r) => (r.err || r.out || "blocked by a spexcode hook").trim()

  // session tracking: the ROOT opencode session is this worker's conversation; child sessions (subagents)
  // are stamped agent_id so a parent's declared state stays out of its subagents' reach (the same
  // discriminator claude's Task subagents carry).
  let rootSession = ""
  const children = new Set()
  const stamp = (sid) => (sid && children.has(sid) ? { agent_id: sid } : {})
  // opencode MINTS its own session id — report it once so the backend stores it as harness_session_id
  // (what reopen() resumes with, \`--session <id>\`). Fire-and-forget; a failure only costs resume-by-id.
  let captured = false
  const capture = (sid) => {
    if (captured || !sid || !recordId) return
    captured = true
    try { spawn(SPEX, ["internal", "opencode-capture", sid], { cwd, env: process.env, stdio: "ignore" }) } catch { /* resume falls back to --continue */ }
  }
  const adopt = (sid) => { if (!rootSession && sid) { rootSession = sid; capture(sid) } }
  const injectPrompt = async (text) => {
    if (!client || !rootSession) throw new Error("no session to prompt")
    await client.session.prompt({ path: { id: rootSession }, body: { parts: [{ type: "text", text }] } })
  }

  // rendezvous daemon: single-connection (a new connect kicks the previous — the claude daemon's contract,
  // which makes the delivery side's atomic reply+repaint chunk decidable). {type:"reply"} injects the text
  // as a prompt into the root session; {type:"repaint"} answers repaint-done (the in-order parse barrier).
  const sockPath = (process.env.CLAUDE_BG_RENDEZVOUS_SOCK || "").trim()
  if (sockPath) {
    try { if (existsSync(sockPath)) unlinkSync(sockPath) } catch { /* stale file from a crashed run */ }
    let conn = null
    const server = createServer((c) => {
      if (conn) { try { conn.destroy() } catch { /* already gone */ } }
      conn = c
      let buf = ""
      c.on("error", () => { /* peer went away — the delivery side handles retries */ })
      c.on("data", async (d) => {
        buf += d.toString("utf8")
        let nl
        while ((nl = buf.indexOf("\\n")) >= 0) {
          const line = buf.slice(0, nl); buf = buf.slice(nl + 1)
          let msg = null
          try { msg = JSON.parse(line) } catch { continue }
          if (msg && msg.type === "reply" && typeof msg.text === "string") {
            try { await injectPrompt(msg.text) } catch { try { c.write(JSON.stringify({ type: "reply-rejected" }) + "\\n") } catch { /* */ } }
          } else if (msg && msg.type === "repaint") {
            try { c.write(JSON.stringify({ type: "repaint-done" }) + "\\n") } catch { /* */ }
          }
        }
      })
    })
    server.on("error", () => { /* socket unavailable — liveness falls back to the agent pid */ })
    server.listen(sockPath)
    server.unref()   // never hold the host process open for our socket; opencode's own loop keeps it alive while it runs
  }

  const toolPayload = (input, output) => {
    const args = { ...((output && output.args) || {}) }
    if (args.filePath !== undefined && args.file_path === undefined) { args.file_path = args.filePath; delete args.filePath }
    const sid = (input && input.sessionID) || ""
    return { ...stamp(sid), tool_name: TOOL_NAMES[(input && input.tool) || ""] || ((input && input.tool) || ""), tool_input: args }
  }

  return {
    event: async ({ event }) => {
      const t = event && event.type
      const p = (event && event.properties) || {}
      if (t === "session.created") {
        const info = p.info || {}
        if (info.parentID) children.add(info.id)
        else if (!rootSession) { adopt(info.id); await dispatchEvent("SessionStart", { source: "startup" }) }
      } else if (t === "session.idle") {
        const sid = p.sessionID || ""
        if (sid && rootSession && sid !== rootSession) return   // a subagent going idle is not this worker's Stop
        adopt(sid)
        const r = await dispatchEvent("Stop", {})
        if (blocked(r)) { try { await injectPrompt(reason(r)) } catch { /* gate reason lost; next idle re-fires it */ } }
      }
    },
    "chat.message": async (input, output) => {
      const sid = (output && output.message && output.message.sessionID) || (input && input.sessionID) || ""
      if (!(sid && children.has(sid))) adopt(sid)
      const text = ((output && output.parts) || []).filter((x) => x && x.type === "text").map((x) => x.text).join("\\n")
      await dispatchEvent("UserPromptSubmit", { ...stamp(sid), prompt: text })
    },
    "tool.execute.before": async (input, output) => {
      const r = await dispatchEvent("PreToolUse", toolPayload(input, output))
      if (blocked(r)) throw new Error(reason(r))   // aborts the tool call — the PreToolUse block contract
    },
    "tool.execute.after": async (input, output) => {
      await dispatchEvent("PostToolUse", toolPayload(input, output))
    },
  }
}
`
}
