import { existsSync, mkdirSync, readFileSync, writeFileSync, realpathSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'

// @@@ pi-harness helpers - the pi-ONLY machinery behind harness.ts's piHarness adapter: the generated
// extension source (pi's shim is a TypeScript extension, not a hooks JSON — pi has no external hook binding;
// its lifecycle surface IS the extension API) and the trust writer (pi's project-trust store,
// ~/.pi/agent/trust.json). Kept out of harness.ts so the adapter table stays scannable; imports NOTHING from
// harness.ts at runtime (no cycle — harness.ts imports us).

// ---------------------------------------------------------------------------------------------------------
// the pi shim = a generated extension at .pi/extensions/spexcode.ts (pi runs .ts extensions natively). It is
// the pi face of dispatch.sh: it synthesizes CLAUDE-SHAPED payloads from pi's extension events — so
// hooks/harness.sh needs NO pi-specific parse arm (pi joins the claude family via the default case) — and
// bridges pi's typed block contract ({ block: true, reason }) onto dispatch.sh's exit-2 contract. Event map:
//   session_start → SessionStart · input → UserPromptSubmit · tool_call → PreToolUse (blockable) ·
//   tool_result → PostToolUse · agent_settled → Stop (exit 2 → the gate's stderr is sent back to the agent
//   as a user message, pi's equivalent of claude's Stop-block continuation).
// It ALSO owns the session's rendezvous socket: sessions.ts launches every ownsRendezvous harness with
// CLAUDE_BG_RENDEZVOUS_SOCK=<rvSock(id)>; the extension binds a line-JSON server there speaking the reclaude
// mini-protocol ({type:reply} → sendUserMessage; {type:repaint} → repaint-done), so claude's liveness
// (socket-listener probe) and delivery (deliverViaRendezvous) work UNCHANGED for pi. Unlike reclaude the
// server is multi-connection, so a liveness probe can never kick a concurrent delivery.
export function piExtensionSource(dispatch: string, spex: string): string {
  return `// generated by spexcode materialize — DO NOT EDIT (regenerated per clone; identity: dispatch.sh)
// SpexCode's pi shim: forwards pi lifecycle events to dispatch.sh as Claude-shaped hook payloads, and serves
// this session's rendezvous socket for prompt delivery + liveness.
import { spawnSync } from "node:child_process"
import { createServer, type Server } from "node:net"
import { unlinkSync } from "node:fs"
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"

const DISPATCH = ${JSON.stringify(dispatch)}
const SPEX = ${JSON.stringify(spex)}
// pi tool names → the Claude tool vocabulary harness.sh parses (unknown names pass through untouched).
const TOOL: Record<string, string> = { read: "Read", edit: "Edit", write: "Write", bash: "Bash" }

export default function spexcode(pi: ExtensionAPI) {
  let sessionId = process.env.SPEXCODE_SESSION_ID || ""

  const dispatchEvent = (event: string, extra: Record<string, unknown> = {}) => {
    const payload = JSON.stringify({ session_id: sessionId, cwd: process.cwd(), hook_event_name: event, ...extra })
    const r = spawnSync("bash", [DISPATCH, "pi", event], {
      input: payload, encoding: "utf8", timeout: 600_000, env: { ...process.env, SPEX },
    })
    return { status: r.status, stdout: r.stdout ?? "", stderr: r.stderr ?? "" }
  }
  const toolFields = (toolName: string, input: unknown) => {
    const tool_input: Record<string, unknown> = { ...(input && typeof input === "object" ? input as Record<string, unknown> : {}) }
    if (typeof tool_input.path === "string" && tool_input.file_path === undefined) tool_input.file_path = tool_input.path
    return { tool_name: TOOL[toolName] ?? toolName, tool_input }
  }

  // the rendezvous control socket — bound as soon as the extension loads so liveness reads online early.
  // Only a governed launch carries the env (sessions.ts rvEnv); a self-launched bare \`pi\` skips this.
  const sock = process.env.CLAUDE_BG_RENDEZVOUS_SOCK
  let srv: Server | undefined
  if (sock) {
    try { unlinkSync(sock) } catch { /* no stale socket — fine */ }
    srv = createServer((c) => {
      let buf = ""
      c.on("error", () => { /* probes disconnect abruptly — expected */ })
      c.on("data", (d) => {
        buf += d.toString("utf8")
        let nl: number
        while ((nl = buf.indexOf("\\n")) >= 0) {
          const line = buf.slice(0, nl)
          buf = buf.slice(nl + 1)
          let msg: { type?: string; text?: string }
          try { msg = JSON.parse(line) } catch { continue }
          if (msg?.type === "reply" && typeof msg.text === "string") pi.sendUserMessage(msg.text, { deliverAs: "steer" })
          else if (msg?.type === "repaint") c.write(JSON.stringify({ type: "repaint-done" }) + "\\n")
        }
      })
    })
    srv.on("error", (e) => console.error(\`spexcode: rendezvous socket failed to bind at \${sock}: \${String(e)}\`))
    srv.listen(sock)
  }

  pi.on("session_start", async (_event, ctx) => {
    sessionId = ctx.sessionManager.getSessionId() || sessionId
    process.env.PI_SESSION_ID = sessionId   // tool subprocesses inherit it → spex CLI knows its session
    dispatchEvent("SessionStart")
  })
  pi.on("input", async (event) => { dispatchEvent("UserPromptSubmit", { prompt: event.text }) })
  pi.on("tool_call", async (event) => {
    const r = dispatchEvent("PreToolUse", toolFields(event.toolName, event.input))
    if (r.status === 2) return { block: true, reason: r.stderr.trim() || "blocked by a SpexCode hook" }
  })
  pi.on("tool_result", async (event) => { dispatchEvent("PostToolUse", toolFields(event.toolName, event.input)) })
  pi.on("agent_settled", async () => {
    const r = dispatchEvent("Stop")
    // exit 2 = the stop gate holds the turn open; its stderr instruction goes back in as a user message —
    // pi's equivalent of claude's Stop-hook block (the gate exits 0 once the contract is satisfied).
    if (r.status === 2 && r.stderr.trim()) pi.sendUserMessage(r.stderr.trim(), { deliverAs: "steer" })
  })
  pi.on("session_shutdown", async () => {
    srv?.close()
    if (sock) { try { unlinkSync(sock) } catch { /* already gone */ } }
  })
}
`
}

// ---------------------------------------------------------------------------------------------------------
// pi trust — make a dispatched/self-launched pi load our project-local extension with zero prompts. pi gates
// EVERY project-local resource (.pi/extensions, .pi/skills, .pi/prompts, .pi/settings.json) behind project
// trust: saved decisions live in ~/.pi/agent/trust.json as a flat { "<canonical dir>": true|false } map, and
// the CLOSEST saved decision on the cwd's parent chain wins (pi trust-manager findNearestTrustEntry). So ONE
// entry keyed by the MAIN CHECKOUT covers every .worktrees/<id> worktree beneath it. The launch additionally
// carries `--approve` (one-run trust) as defence for a worktree living OUTSIDE the checkout. Writes are
// idempotent and surgical: other projects' decisions are untouched; a corrupt trust.json FAILS LOUD rather
// than being clobbered; remove only deletes a `true` we could have written, never a user's saved "false".

// pi has no config-dir env of its own (hardcoded ~/.pi/agent) — SPEXCODE_PI_AGENT_DIR is OUR test seam only.
const piAgentDir = () => process.env.SPEXCODE_PI_AGENT_DIR || join(homedir(), '.pi', 'agent')
// pi canonicalizes trust keys (realpath); mirror it so our key matches its lookup.
const canonical = (p: string) => { try { return realpathSync(p) } catch { return p } }

function readTrust(file: string): Record<string, unknown> {
  if (!existsSync(file)) return {}
  const raw = readFileSync(file, 'utf8')
  try { return JSON.parse(raw) as Record<string, unknown> } catch (e) {
    throw new Error(`${file} is not valid JSON — refusing to rewrite pi's trust store: ${String(e)}`)
  }
}

export function writePiTrust(proj: string): void {
  const dir = piAgentDir()
  const file = join(dir, 'trust.json')
  const key = canonical(proj)
  const data = readTrust(file)
  if (data[key] === true) return   // already trusted — no churn
  data[key] = true
  mkdirSync(dir, { recursive: true })
  writeFileSync(file, JSON.stringify(data, null, 2) + '\n')
}

export function removePiTrust(proj: string): void {
  const file = join(piAgentDir(), 'trust.json')
  if (!existsSync(file)) return
  const key = canonical(proj)
  const data = readTrust(file)
  if (data[key] !== true) return   // absent, or a user's own "do not trust" — never touch it
  delete data[key]
  writeFileSync(file, JSON.stringify(data, null, 2) + '\n')
}
